const mongoose = require('mongoose');
const CourseSchema = new mongoose.Schema({
   courseName:{
    type:String,
    required:true,
    trim:true,
   },
   courseDescription:{
    type:String,
    trim:true,
   },
   instructor:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"User",
    required:true,
   },
   whatYouWillLearn:{
    type:String,
    trim:true,
   },
   courseContent:[{
    type:mongoose.Schema.Types.ObjectId, 
    ref:"Section",
   }],
   ratingAndReviews:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"RatingAndReview",
   }],
   price:{
    type:String,
    required:true,
   },
   tag:{
      type:[String],
      required:true,
   },
   thumbnail:{
    type:String,
   },
   Category:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Category",
   },
   studentsEnrolled:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"User",
    required:true,
   }],
   instructions:{
      type:[String],
   },
   status:{
      type:String,
      enum:["Draft","Published"]
   }

});

module.exports = mongoose.model("Course", CourseSchema);